#theme: jekyll-theme-cayman
#theme: minimal
# title: Waggle -- An Open Platform for AI@Edge Computing
theme: jekyll-theme-cayman
title: AI@Edge and Software-Defined Sensors for National Research Infrastructure
description: April 29-30, 2019, Argonne National Laboratory
